### ISSUE TITLE
Compiler pour iOS

### ISSUE THREAD

**Issue by DocSystem** [EduWireApps/ynotes#15]
Je trouve le principe de l'app génial et, ayant un Mac, j'ai essayé de compiler l'application pour iOS et de la lancer dans le simulateur avec ``flutter run``, mais Flutter me renvoie une erreur à chaque fois ! Quelqu'un sait-il comment résoudre ce problème ?
Merci d'avance ! Voilà les logs :
```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                              1,1s
CocoaPods' output:

↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A advance_pdf_viewer
      A awesome_notifications
      A battery_optimization
      A flutter_file_dialog
      A image_picker
      A sqflite
      A webview_flutter
      R file_picker
      - Flutter
      - background_fetch
      - connectivity
      - ext_storage
      - flutter_local_notifications
      - flutter_secure_storage
      - open_file
      - package_info
      - path_provider
      - permission_handler
      - sensors
      - share
      - shared_preferences
      - url_launcher
      - video_player
      - wakelock

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `advance_pdf_viewer` from
    `.symlinks/plugins/advance_pdf_viewer/ios`
    -> Fetching podspec for `awesome_notifications` from
    `.symlinks/plugins/awesome_notifications/ios`
    -> Fetching podspec for `background_fetch` from
    `.symlinks/plugins/background_fetch/ios`
    -> Fetching podspec for `battery_optimization` from
    `.symlinks/plugins/battery_optimization/ios`
    -> Fetching podspec for `connectivity` from
    `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `ext_storage` from
    `.symlinks/plugins/ext_storage/ios`
    -> Fetching podspec for `flutter_file_dialog` from
    `.symlinks/plugins/flutter_file_dialog/ios`
    -> Fetching podspec for `flutter_local_notifications` from
    `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_secure_storage` from
    `.symlinks/plugins/flutter_secure_storage/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `open_file` from `.symlinks/plugins/open_file/ios`
    -> Fetching podspec for `package_info` from
    `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `sensors` from `.symlinks/plugins/sensors/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from
    `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from
    `.symlinks/plugins/video_player/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
    -> Fetching podspec for `webview_flutter` from
    `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod
    "awesome_notifications":
      In Podfile:
        awesome_notifications (from
        `.symlinks/plugins/awesome_notifications/ios`)

    Specs satisfying the `awesome_notifications (from
    `.symlinks/plugins/awesome_notifications/ios`)` dependency were found, but
    they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:32
    8:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:31
    0:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:30
    8:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:30
    8:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:68
    4:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:25
    4:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:18
    2:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:i
    n `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:
    in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analy
    zer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.
    rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analy
    zer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analy
    zer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:41
    4:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:23
    9:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.
    rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:23
    8:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:16
    0:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install
    .rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in
    `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:i
    n `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top
    (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target
    `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 12 Pro Max.
```

**Comment by ModernChocolate** [comment]
Bonsoir, cela fait longtemps que je n'ai pas compilé l'application pour iOS. Il semblerait que votre problème soit lié à une mauvaise configuration au moment du build. Les logs spécifient que la dépendance awesome_notifications `required a higher minimum deployment target.`
Je vous suggère donc de compiler l'application pour une version d'iOS (vous déployez actuellement par défaut pour 8.0) plus récente en définissant la version cible depuis XCode.

**Comment by ModernChocolate** [comment]
Le déploiement iOS étant fonctionnel, le build a été testé sans issues sur plusieurs machines (y compris sur la VM GitHub actions). Je ferme donc cette issue.
